CREATE TABLE DANAGRAF.TDIVISE (
  SIGLADIV	CHARACTER(3)	NOT NULL,
  CAMBIODV	DECIMAL(11, 6)	NOT NULL,
  DESCDIVI	CHARACTER(20)	NOT NULL	DEFAULT ,
  CODDIVIS	CHARACTER(2)	NOT NULL,
  DECIDIVI	CHARACTER(1)	NOT NULL	DEFAULT ,
  DIVIBANC	CHARACTER(3)	NOT NULL	DEFAULT ,
  DIVIPREZ	CHARACTER(1)	NOT NULL	DEFAULT ,
  CODDIVRI	CHARACTER(2)	NOT NULL	DEFAULT ,
  RAPPCAMB	DECIMAL(5, 0)	NOT NULL	DEFAULT ,
  CODDIGTM	CHARACTER(2)	NOT NULL	DEFAULT ,
  FLAGEURO	CHARACTER(1)	NOT NULL	DEFAULT ,
  SLDIVBAN	CHARACTER(3)	NOT NULL	DEFAULT ,
  CDDIVSCA	CHARACTER(2)	NOT NULL	DEFAULT ,
  FLDIVINT	CHARACTER(1)	NOT NULL	DEFAULT ,
  VBDIVSCA	CHARACTER(2)	NOT NULL	DEFAULT 
  ) 
  IN DANAGRAF_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;