CREATE TABLE DANAGRAF.TTEMPITRANS (
  CODUTENT	CHARACTER(6)	NOT NULL,
  CODITRAN	CHARACTER(4)	NOT NULL,
  CODIFUNZ	CHARACTER(2)	NOT NULL,
  INILAVOR	CHARACTER(4)	NOT NULL	DEFAULT ,
  CODSOCIE	CHARACTER(2)	NOT NULL	DEFAULT ,
  CODDEPOS	CHARACTER(2)	NOT NULL	DEFAULT ,
  NOTENOTE	CHARACTER(60)	NOT NULL	DEFAULT ,
  NOTENOT1	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLA200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLB200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLC200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLD200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLE200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLF200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLG200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLH200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLI200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLJ200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLK200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLL200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLM200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLN200	CHARACTER(200)	NOT NULL	DEFAULT ,
  FILLO200	CHARACTER(200)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT 
  ) 
  IN DANAGRAF_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;