CREATE TABLE DLOGISTI.TSERVIZI (
  CODSERVI	CHARACTER(6)	NOT NULL,
  DESSERVI	CHARACTER(40)	NOT NULL	DEFAULT ,
  UNMISURA	CHARACTER(2)	NOT NULL	DEFAULT ,
  TIPSERVI	CHARACTER(1)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT ,
  CONTODCD	CHARACTER(6)	NOT NULL	DEFAULT ,
  CONTODCA	CHARACTER(6)	NOT NULL	DEFAULT ,
  CENCOSTA	CHARACTER(5)	NOT NULL	DEFAULT ,
  ESENTIVA	CHARACTER(1)	NOT NULL	DEFAULT ,
  CONTPROV	CHARACTER(6)	NOT NULL	DEFAULT 
  ) 
  IN DLOGISTI_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;