CREATE TABLE DANAGRAF.TCENCOSTO (
  CODSOCIE	CHARACTER(2)	NOT NULL,
  CENCOSTO	CHARACTER(5)	NOT NULL,
  DESCENCO	CHARACTER(30)	NOT NULL,
  RAGCENCO	CHARACTER(3)	NOT NULL	DEFAULT ,
  ANNULLAM	CHARACTER(1)	NOT NULL	DEFAULT ,
  NEWCENCO	CHARACTER(5)	NOT NULL	DEFAULT ,
  CENCOLIS	CHARACTER(5)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT ,
  CDMCAGTM	CHARACTER(1)	NOT NULL	DEFAULT ,
  CDAREGTM	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDDIPGTM	CHARACTER(1)	NOT NULL	DEFAULT ,
  CDUBIGTM	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDLINGTM	CHARACTER(2)	NOT NULL	DEFAULT ,
  SIGLCALE	CHARACTER(3)	NOT NULL	DEFAULT ,
  GRUPSIGE	CHARACTER(1)	NOT NULL	DEFAULT ,
  CDDIVISI	CHARACTER(1)	NOT NULL	DEFAULT 
  ) 
  IN DANAGRAF_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;