CREATE TABLE DANAGRAF.TPAESI (
  CODPAESE	CHARACTER(3)	NOT NULL,
  CODILING	CHARACTER(1)	NOT NULL	DEFAULT ,
  PAESBANC	CHARACTER(3)	NOT NULL	DEFAULT ,
  PAESEISO	CHARACTER(2)	NOT NULL	DEFAULT ,
  FLPAECEE	CHARACTER(1)	NOT NULL	DEFAULT ,
  FLPAEORI	CHARACTER(1)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT ,
  SLPAEGTM	CHARACTER(3)	NOT NULL	DEFAULT ,
  PRFINTER	CHARACTER(5)	NOT NULL	DEFAULT ,
  GRUPPAES	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDMCAREG	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDAREREG	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGCEN	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGTRA	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGFOC	CHARACTER(2)	NOT NULL	DEFAULT ,
  CODPAGVB	CHARACTER(3)	NOT NULL	DEFAULT ,
  SIGPAGVB	CHARACTER(2)	NOT NULL	DEFAULT ,
  CODPARUS	CHARACTER(3)	NOT NULL	DEFAULT ,
  CDRAGLIS	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGSTA	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGLIC	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDRAGLIF	CHARACTER(2)	NOT NULL	DEFAULT 
  ) 
  IN DANAGRAF_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;