CREATE TABLE DLOGISTI.TRIGORDILOGI (
  AANUMORD	CHARACTER(8)	NOT NULL,
  NRRIGORD	DECIMAL(5, 0)	NOT NULL	DEFAULT ,
  CODSERVI	CHARACTER(6)	NOT NULL	DEFAULT ,
  UNMISURA	CHARACTER(2)	NOT NULL	DEFAULT ,
  QTAORDIN	DECIMAL(9, 2)	NOT NULL	DEFAULT ,
  PREZZORD	DECIMAL(11, 4)	NOT NULL	DEFAULT ,
  IMPORDIN	DECIMAL(13, 2)	NOT NULL	DEFAULT ,
  NOTENOTE	CHARACTER(40)	NOT NULL	DEFAULT ,
  CENCOSTD	CHARACTER(5)	NOT NULL	DEFAULT ,
  CENCOSTA	CHARACTER(5)	NOT NULL	DEFAULT ,
  RIFECLIE	CHARACTER(15)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT ,
  DTANNULL	CHARACTER(8)	NOT NULL	DEFAULT ,
  IMPORIVA	DECIMAL(13, 2)	NOT NULL	DEFAULT 
  ) 
  IN DLOGISTI_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;

ALTER TABLE DLOGISTI.TRIGORDILOGI
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
