CREATE TABLE DCONTCLI.TSOLLECITI (
  CODSOCIE	CHARACTER(2)	NOT NULL,
  GRUPSOLL	CHARACTER(1)	NOT NULL,
  TIPOSOLL	CHARACTER(1)	NOT NULL,
  CODILING	CHARACTER(1)	NOT NULL,
  NUMPROG5	DECIMAL(5, 0)	NOT NULL,
  RIGASOLL	CHARACTER(80)	NOT NULL
  ) 
  IN DCONTCLI_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;