CREATE TABLE DANAGRAF.TMESSAGGI (
  CODERROR	CHARACTER(5)	NOT NULL,
  CODILING	CHARACTER(1)	NOT NULL,
  MSGERROR	CHARACTER(60)	NOT NULL,
  TIPOMESS	CHARACTER(1)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT 
  ) 
  IN DANAGRAF_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;