CREATE TABLE DLOGISTI.TORDILOGI (
  AANUMORD	CHARACTER(8)	NOT NULL,
  CODCLIEN	CHARACTER(5)	NOT NULL	DEFAULT ,
  CODSOCIE	CHARACTER(2)	NOT NULL	DEFAULT ,
  CDDIVISI	CHARACTER(1)	NOT NULL	DEFAULT ,
  DTCARORD	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODDIVIS	CHARACTER(2)	NOT NULL	DEFAULT ,
  TIPSERVI	CHARACTER(1)	NOT NULL	DEFAULT ,
  FLAGAUTO	CHARACTER(1)	NOT NULL	DEFAULT ,
  FLAGGIVA	CHARACTER(1)	NOT NULL	DEFAULT ,
  CONTODCE	CHARACTER(6)	NOT NULL	DEFAULT ,
  DTEVAORD	CHARACTER(8)	NOT NULL	DEFAULT ,
  AANUMFAT	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTFATTUR	CHARACTER(8)	NOT NULL	DEFAULT ,
  NRPREATT	CHARACTER(10)	NOT NULL	DEFAULT ,
  DTPREATT	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTCREAZI	CHARACTER(8)	NOT NULL	DEFAULT ,
  DTULTVAR	CHARACTER(8)	NOT NULL	DEFAULT ,
  CODUTVAR	CHARACTER(6)	NOT NULL	DEFAULT ,
  DTANNULL	CHARACTER(8)	NOT NULL	DEFAULT ,
  SOCIEMER	CHARACTER(2)	NOT NULL	DEFAULT ,
  DATAESTR	CHARACTER(8)	NOT NULL	DEFAULT ,
  AAMMCOMP	CHARACTER(6)	NOT NULL	DEFAULT ,
  FLAGSOSP	CHARACTER(1)	NOT NULL	DEFAULT ,
  CODUTEVB	CHARACTER(6)	NOT NULL	DEFAULT ,
  ESENTIVA	CHARACTER(1)	NOT NULL	DEFAULT ,
  FLORDIVB	CHARACTER(1)	NOT NULL	DEFAULT 
  ) 
  IN DLOGISTI_TS
  COMPRESS YES ADAPTIVE
  ORGANIZE BY ROW;